name: Exit3x
favicon: null
layout_spectrum: 0.9719257254619151
typography_spectrum: 0.14990133023820817
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.15770772355608642
  lightness: 0.6863207714632154
  saturation: 0.9832145557738841
  rhythmicContrast: 0.2062940737232566
purpose: []
